### ISSUE TITLE
Make Shift+V have paradropping units delay parachute opening until e.g. 150m ATL

### ISSUE THREAD

**Issue by ImperialAlex** [ArmaAchilles/Achilles#112]
I really love the paradrop feature that one can trigger by pressing V on an aircraft. Together with setFlyInHeight it makes for a great simulation of a static line parachute drop (instant parachute deployment). 

However, sometimes I would like to have the AI simulate a High Altitude Low Opening (HALO) jump, e.g. in situations where enemy fire would pick them all off in the sky with a "traditional" jump.
Therefore I'd like to suggest extending the feature by adding a second keybinding that will have them delay their parachute opening until X meters ATL (where X is some number around 200-ish, might need some testing so they don't kill or injure themselves ^^)

**Comment by oOKexOo** [comment]
Actually, there is already an unused HALO script somewhere in the source code. Not sure if it works for AI thought. I'm actually surprised I didn't found it on one of the task lists.

**Comment by mcrow900** [comment]
If you can't find a better way, AI automatically deploy parachutes when added. So if you were to eject them from the plane without a parachute, then add a chute backpack at 200m, they would deploy it immediately.

**Comment by oOKexOo** [comment]
The idea of an additional keybinding was abandoned. Instead it will be the general behaviour for AI to deploy the chute at around 150 m for high altitudes.
