### ISSUE TITLE
USS Freedom cannot be moved

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/Achilles#191]
When spawned, you can't move the ship. It will only move the object's size silhouette thing.

**Comment by unhappytroll** [comment]
mmmmm, as far as I know, it is created that way by BI, to be placed in Eden and to be not movable - because of bad glue assembly.

**Comment by CreepPork** [comment]
@unhappytroll It was movable but not anymore, therefore something is broken.

**Comment by CreepPork** [comment]
Seems like BI broke this, as in 0.0.9c where it worked, now it doesn't work with the latest version of Arma 3.

**Comment by unhappytroll** [comment]
May be that was done for  the catapult crashing issue.

**Comment by oOKexOo** [comment]
You would have to update the position manually with BIS_fnc_Carrier01PosUpdate, but it breaks the catapult. I already wasted a lot of time on the implementation of this module and I therefore recommend to postpone this issue till there is a more reliable position update function.

**Comment by oOKexOo** [comment]
If you won't mind, I'll close that issue.
