### ISSUE TITLE
Changing unit name does not change unit name in ACE3

### ISSUE THREAD

**Issue by DeliciousJaffa** [ArmaAchilles/Achilles#300]
**Arma 3 Version:** `1.82.144647` stable
**CBA Version:** `3.6.1` stable 
**Achilles Version:** `1.0.2` stable

**Mods:**
```
- CBA_A3
- Achilles
- ACE 3
```

**Description:**
- Changing names of units does not adjust their name in ACE (i.e. Medical menu or dogtags).
- This is more of an issue with ACE itself, however ACE would probably avoid overriding Zeus functionality and will likely not be "fixed" within ACE

**Steps to reproduce:**
- Double click unit
- Change name
- Open ACE medical menu on unit

**Where did the issue occur?**
- Dedicated

**How to fix this**
- When the user closes the edit unit dialog with OK,  [`ace_common_fnc_setName`](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_setName.sqf) needs to be called after the unit's name has changed.

**Comment by RoqueTHEGAMER** [comment]
Dog tags still have the wrong name even after use of ace_common_fnc_setName, medical menu and selection are working.

**Comment by CreepPork** [comment]
@RoqueTHEGAMER 
We can't do anything about that as it's an ACE3 issue and it's their framework, not ours.
