### ISSUE TITLE
Error in Achilles_fnc_LaunchCM when using it with any RHS Littlebird

### ISSUE THREAD

**Issue by cineafx** [ArmaAchilles/Achilles#309]
**Arma 3 Version:** `1.82` (stable)  
**CBA Version:** ` 3.7.0` (stable)  
**Achilles Version:** `1.0.2` (stable)  

**Mods:**
```
- CBA_A3
- Achilles
- RHSUSAF: 0.4.5
```

**Description:**
- When using the _Selected unit throws smoke / uses countermeasure_ feature on any RHSUSAF Littlebird variation (AH-6M, AH-6M-H, AH-6M-L, AH-6M-M, MH-6M and OH-6M) the following error occurs:
-  `Error Undefined variable in expression: _cmweapon` (Details in the RPT)

**Steps to reproduce:**
- Start any map / gamemode with a curator interface.
- Place any of the RHS Littlebirds.
- Press button to deploy countermeasures of the selected vehicle. Default _c_.

**Where did the issue occur?**
- Should occur in all modes.
- But only tested / confirmed in Self-Hosted Multiplayer, Singleplayer and Editor (Singleplayer).

**RPT log file:**
- Relevant part of the RPT: https://pastebin.com/waUEjYqv
- Full RPT: https://pastebin.com/vTGjtL4Q

**Comment by oOKexOo** [comment]
It's due to a missing exception handling. The exception is that countermeasure weapon class for that particular aircraft is not whitelisted.

**Comment by CreepPork** [comment]
It can also happen for Russian tanks from RHS.

**Comment by oOKexOo** [comment]
My statement in a more general way: If any smoke/CM launcher magazines are found, but the weapon is not whitelisted, you will get this error.
