### ISSUE TITLE
"Lock Doors" does not work on JBAD houses (LYTHIUM map)

### ISSUE THREAD

**Issue by Alexanderful** [ArmaAchilles/Achilles#315]
**Arma 3 Version:** `1.82.144710` (stable)  
**CBA Version:** `3.70` (stable)  
**Achilles Version:** `1.02` (stable)  

**Mods:**
```
- CBA_A3
- Ace
- Achilles
```

**Description:**
- Lock Door feature does not work on JBAD houses on the LYTHIUM map. It does work on some of the structures but I believe it does not work on any of the JBAD buildings.

**Steps to reproduce:**
- Load the LYTHIUM map.
- Open Zeus
- Navigate to a JBAD house
- Attempt to lock doors
- Message says 0 doors were locked

**Where did the issue occur?**
- Eden Editor/SP

**RPT log file:**
- N/A

**Comment by oOKexOo** [comment]
We checked the config. It seems that JBAD houses cannot be locked.
