### ISSUE TITLE
Unexpected teleportation when using switch unit

### ISSUE THREAD

**Issue by oOKexOo** [ArmaAchilles/Achilles#330]
**Issue (Noir Lime):**
> Found a bug: 
> When you try to switch unit, sometimes it teleports the unit to Zeus' camera position, thus killing the unit via fall damage if the camera is high.
> Sometimes it happens, sometimes it doesn't. It's really inconsistent.

**Possible Solution:**

> Well, we could change the position of the camera to the unit's position right before the switch.

**Comment by CreepPork** [comment]
I’m still not really sure about this issue. Perhaps we should investigate the issue more before we add a “fix” that could have adverse effects.

**Comment by oOKexOo** [comment]
It has no effect for those that have no issues. So why bother? While I wasn't able to reproduce the issue, I trust Noir Lime's report. Why not add something that likely fixes what he reproted, but does not change the behaviour of the module in a noticeable way.
