### ISSUE TITLE
Cargo/object inventory Zeus access not working

### ISSUE THREAD

**Issue by Siliconpot** [ArmaAchilles/Achilles#333]
**Arma 3 Version:** '1.82.144710' (stable)  
**CBA Version:** '3.7.1.180604' (stable, steam workshop)  
**Achilles Version:** '1.1.0' (stable, steam workshop)  

**Mods:**
- CBA_A3
- Achilles

**Description:**
- Quite simple: Unable to edit any inventory (aka cargo) in Zeus mode with Achilles. An error pops up:
https://ibb.co/mOVa2J

**Steps to reproduce:**
1. Place any container/vehicle either in Zeus or Eden
2. Try to access that container/vehicle cargo via the Achilles/Zeus interface
3. Be met with an error and empty inventory screen like in the picture linked in description.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by oOKexOo** [comment]
There must be something essential missing here. The issue described is not reproducible.
I made a simple setup in Eden with one playable unit that owns a curator module and placed a Gorgon.
I could access the inventory without any issues as a server host.

**Comment by Siliconpot** [comment]
I've reinstalled both the mods, and the game now, still facing the same issue - I haven't tried with non-steam workshop versions though, might try that next.

**Comment by CreepPork** [comment]
I can't repro the issue either. Can you add your .rpt log or something to give us a lead to go onto?

**Comment by TheRadiumDude** [comment]
I can't reproduce this issue on my side either. Inventory appears as normal with no error, same environment.

**Comment by oOKexOo** [comment]
The error he captured is refering to this line:
https://github.com/ArmaAchilles/Achilles/blob/7441e44e2a97254774d3ec41e1eb15a11fcdf826/%40AresModAchillesExpansion/addons/ui_f/scripts/RscAttributeInventory.sqf#L114
The `_x` is an element from the array below:
https://github.com/ArmaAchilles/Achilles/blob/7441e44e2a97254774d3ec41e1eb15a11fcdf826/%40AresModAchillesExpansion/addons/ui_f/scripts/RscAttributeInventory.sqf#L131
One has therefore to conclude that he has an `cfgPatches` subclass that is different from ours or we have not. Probably a 3rd party addon that he forgot to mention.

**Comment by Siliconpot** [comment]
Sorry for the slow response, I was mildly occupied during the weekend. However...
I'm unable to reproduce this anymore, and only things I've done between then and now are:
-Rebooted computer, and
-Updated graphics drivers (nvidia)
-Reinstalled Wreckfest

I'll now go through some mods to see if any of them re-trigger this.

**Comment by Siliconpot** [comment]
I've found a possible culprit: The Australia -terrain http://www.armaholic.com/page.php?id=28882
I do not know how did it stick even after the mod was off before.

**Comment by oOKexOo** [comment]
Confirmed it is the Australia mod. It has an illegal entry in `configfile >> "CfgPatches" >> "ausextras_signs" >> "units"`.
