### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by rpgkayak** [ArmaAchilles/Achilles#338]
**Arma 3 Version:** N/A  
**CBA Version:** N/A  
**Achilles Version:** N/A 

**Mods:**
```
N/A
```

**Description:**
I'm sort of embarrassed to post here, but all the Web and Steam pages said this was the place. It's not an issue with code, bur rather a documentation error on this page:

https://github.com/ArmaAchilles/Achilles/wiki/Custom-Music

I was trying to get this to work on one of my missions and it kept failing, so I followed a link to the BIKI entry for custom music and discovered there's a discrepancy in the last line of code. The Achilles page reads:

sound[] = {"music\Ambient08_Reforger.ogg", db+10, 1.0};

And the BIKI reads:

sound[]	= { "\music\ludwig9.ogg", db + 10, 1.0 };

The missing back slash fixed everything on my end and totally elevated the experience of the players I was curating for. I hope this is helpful - I love the Achilles mod and hope to see it continue to grow and succeed. I couldn't curate without it!

To see more information about this issue template go to our [wiki](https://github.com/ArmaAchilles/AresModAchillesExpansion/wiki/Issue-Template) page.

**Comment by oOKexOo** [comment]
The documentation is correct. It refers to how to add custom music in a mission, not from an addon.
The backslash at the beginning is used to refer to an addon. Without the backslash you refer to a file in the mission folder (see [BIKI](https://community.bistudio.com/wiki/Script_Path)).

**Comment by CreepPork** [comment]
@oOKexOo That should probably be noted in the docs, no?

**Comment by CreepPork** [comment]
Fixed documentation.
