### ISSUE TITLE
AI reinforcements Rope Repel via ACE first then AR if both exist OR selectable

### ISSUE THREAD

**Issue by ColdEvul** [ArmaAchilles/Achilles#342]
**Suggestion:**
- When using the AI reinforcement module and use helicopter insertion and have both ACE and AR repel systems present the mission should fist select the ACE repel.
- Alternatively CBA Settings selectable for user preference.

**Comment by CreepPork** [comment]
AR rappeling has priority due to ACE rappeling not being as stable as AR in multiplayer.

**Comment by ColdEvul** [comment]
We found vice versa after testing;
We got a 30% leg brake on AR while 0% on ACE Repel
Tested with 2 8man squads jumping from two RHS Black Hawks at the same time 2 at the time with 4 second delay on each jump

**Comment by CreepPork** [comment]
To be honest, giving players choice would be good but I don't get one thing - why would you want to use ACE rappelling if you have AR loaded?

**Comment by oOKexOo** [comment]
Why on earth would you have advanced rappelling loaded when you don't use it?

**Comment by ColdEvul** [comment]
We use it to be able to repel down wall and object.
The ACE helo repel for are more immersive.

**Comment by CreepPork** [comment]
But you are talking about Advanced Urban Rappeling which is not used for helicopters.

**Comment by ColdEvul** [comment]
Ha what tho you know did not know they were separate xD
Things that happens when you have a community mod pack and miss one part.

**Comment by CreepPork** [comment]
No, stuff can still be changed.

**Comment by oOKexOo** [comment]
How so? Providing an extra layer for configurations is unnecessary, as you either load or unload AR. It makes sense that AR is prioritized.
