### ISSUE TITLE
Vehicle Menu Issues

### ISSUE THREAD

**Issue by DarkEthanol** [ArmaAchilles/Achilles#357]
**Mods:**
- CBA_A3
- Achilles
- ACE
- RHS
- 3CB

**Description:**
- After the latest update, the Achilles mod has been causing some problems in Zeus with vehicles. When going into the vehicle settings, it then automatically sets the Engine to on, the lights to on and the locks to on. The driver is unable to turn off the lights or engine in the vehicle, neither is the zeus via the menu.

**Where did the issue occur?**
Dedicated multiplayer

**Comment by oOKexOo** [comment]
First of all reduce the mod set to a minimum (CBA+Achilles; additional mods only if they are clearly related to the issue). I was unable to reproduce the issue with CBA+Achilles. Note that the latest update (1.0.3) made no changes to the vehicle settings.
Apart from the few additional mods, something is still different in your setup. I need a step by step procedure from you (make sure to use an official Zeus mission).

**Comment by oOKexOo** [comment]
Stale... If it's still a thing, let us know.
