### ISSUE TITLE
Feature Request: Add datalink & ace laser codes to laser designation module

### ISSUE THREAD

**Issue by Snak3Doc** [ArmaAchilles/Achilles#358]
A module that when placed paints a laser target on that spot that stays active till its deleted by Zeus, had this idea while trying to use the new cruise missile from Zeus, but it has plenty of other applications. 
Would need to have data linking enabled like a vehicle mounted lasers (VLS cant target handheld laser without LOS)

Ideally it would incorporate a small UI for setting ace laser codes as well

**Comment by CreepPork** [comment]
Laser targets are already implemented into Achilles in the _Create Target_ module.

**Comment by Snak3Doc** [comment]
Thanks I hadn't seen that, I'll edit the title to reflect the backlog for laser codes

**Comment by CreepPork** [comment]
The data link is also available in the vehicle attribute page.

**Comment by oOKexOo** [comment]
I recently extended the artillery module to VLS.
It doesn't even need a laser target in that case.
I assume it makes that request obsolete, doesn't it?

**Comment by Snak3Doc** [comment]
Yea we can just use grid refs for it now thanks Kex
