### ISSUE TITLE
Duplicate strings stringtable.xml

### ISSUE THREAD

**Issue by NorXAengell** [ArmaAchilles/Achilles#360]
Hi,

I want to rework the french translation and it seems the stringtable has some string duplicate.

line 2433:
      <Key ID="STR_THERMALS">
        <Original>Thermal optics</Original>
        <English>Thermal optics</English>
        <French>Caméra thermique</French>
		<Russian>ИК оптика</Russian>
        <German>Wärmebildkamera</German>
      </Key>
and line 2468: 
      <Key ID="STR_THERMALS">
        <Original>Thermal optics</Original>
        <English>Thermal optics</English>
        <French>Caméra thermique</French>
		<Russian>ИК оптика</Russian>
        <German>Wärmebildkamera</German>
      </Key>

Also line 1548:
<Key ID="STR_AMMO">
        <Original>Ammo</Original>
        <English>Ammo</English>
        <French>Munition</French>
        <Russian>Боеприпасы</Russian>
        <German>Munition</German>
      </Key>
and line 2631:
<Key ID="STR_AMMO">
        <Original>AMMO</Original>
        <English>AMMO</English>
		<French>MUNITION</French>
		<German>MUNITION</German>
      </Key>

Thanks for the correction so i can work on the translation ;).

**Comment by CreepPork** [comment]
The ammo lines are different due to one being for the attribute button (toUpper is unavailable) and another ammo line is for other use cases where you don't want the uppercase one.

As for the Thermal Optics one, you should take a look at the code if it contains the key.

**Comment by NorXAengell** [comment]
My bad, i didn't see most of my message avec been deleted....
The problem is the 2 first sentence has the same <Key ID="STR_AMMO"> key string
And the second two have both <Key ID="STR_THERMALS">

I think it should be diferenciated no ? Like "STR_AMMO1" "STR_AMMO2" etc...

Sorry for the first incomplete message  -_-.

**Comment by NorXAengell** [comment]
My bad, i didn't see most of my message avec been deleted....
The problem is the 2 first sentence has the same "STR_AMMO" key string
And the second two have both "STR_THERMALS"

I think it should be diferenciated no ? Like "STR_AMMO1" "STR_AMMO2" etc...

Sorry for the first incomplete message  -_-.

**Comment by CreepPork** [comment]
They are already differenced  - one is named `STR_AMAE_AMMO_UPPER` and the other one is `STR_AMAE_AMMO`.

**Comment by CreepPork** [comment]
`STR_AMMO1` is a lot more unclear.

**Comment by CreepPork** [comment]
I'm sorry but the line numbers don't match master, on what branch are you?

**Comment by NorXAengell** [comment]
The default branch master , it's not the latest ?

**Comment by CreepPork** [comment]
What commit are you on?

**Comment by NorXAengell** [comment]
Uhhh sorry i don't understand very well how github work, so i have just clone it on the main page to my desktop github and check the master branch...

In fact even with following the instruction of "Basic Steps" it seems i'm always with the wrong version -_-...

**Comment by oOKexOo** [comment]
Your fork was out of date. I created a PR that will update your fork.
