### ISSUE TITLE
Feature Request: Hotkey for Chatter Module

### ISSUE THREAD

**Issue by TheRadiumDude** [ArmaAchilles/Achilles#366]
It could be useful to have a hotkey for the chatter module, especially judging how time-consuming it can be to place a chatter module on an unit in a moving vehicle, in situations where the Zeus must time everything correctly.

**Comment by callofmarty** [comment]
Do you mean module that will allow you as zeus, to hear players when placed near them? and maybe attached by attach module.

**Comment by CreepPork** [comment]
@callofmarty 
No, it will work exactly as the Chatter module under AI Behaviours only triggered via a keybinding.

**Comment by callofmarty** [comment]
Ok, is it possible somehink like i suggested? I should probably create feature request...
