### ISSUE TITLE
Vanilla dialogs have scroll bars

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/Achilles#379]
https://gyazo.com/5a8dcc9e7d1bc0b3ec8749b61837c0f2

https://gyazo.com/5d76b542c00c3b02086d77cd3cc90984

**Comment by oOKexOo** [comment]
Fixed for your two examples, but I need to have another look on the inventory attribute window.

**Comment by oOKexOo** [comment]
The max height for the attribute window has been adjusted in #385, however for larger GUI settings than `normal`, you will inevitably get scroll bars to fit the dialog inside the display.

**Comment by CreepPork** [comment]
> The max height for the attribute window has been adjusted in #385, however for larger GUI settings than `normal`, you will inevitably get scroll bars to fit the dialog inside the display.

That is acceptable.
