### ISSUE TITLE
Holding Alt should reflect changes in the include crew checkbox

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/Achilles#380]
https://gyazo.com/a67c703936811099036bf681acaaa6a8

**Comment by oOKexOo** [comment]
Maybe we have to even get rid of that keybinding. It doesn't detect the release when you tab, which is very annoying.

**Comment by oOKexOo** [comment]
The said bug was already present in the shortcut for switch unit. It could be resolved with the `MouseButtonDblClick` event handler, which also passes the states of CTRL, ALT and SHIFT.
If you want to keep the toggle include crew feature, I suggest to use `onMouseButtonClick` and detect the additional keys in there. This solution however restricts the set of valid keybindings to CTRL, ALT and SHIFT. Furthermore, this very ticket is no longer doable.

**Comment by CreepPork** [comment]
> Maybe we have to even get rid of that keybinding. It doesn't detect the release when you tab, which is very annoying.

That's exactly why there should be some kind of feedback to the user.

**Comment by CreepPork** [comment]
> The said bug was already present in the shortcut for switch unit. It was resolved with the `MouseButtonDblClick` event handler, which also passes the states of CTRL, ALT and SHIFT.
> If you want to keep the toggle include crew feature, I suggest to use `onMouseButtonClick` and detect the additional keys in there. This solution however restricts the set of valid keybindings to CTRL, ALT and SHIFT. Furthermore, this very ticket is no longer doable.

You are talking about something different, your statement does not affect this particular issue. I had already implemented the button switching in my PR but you removed it.

https://github.com/ArmaAchilles/Achilles/blob/484bae572b7bb42cbbf6a81e1b71c86de883b0e6/%40AresModAchillesExpansion/addons/settings_f/scripts/keybindings.sqf#L154

https://github.com/ArmaAchilles/Achilles/blob/484bae572b7bb42cbbf6a81e1b71c86de883b0e6/%40AresModAchillesExpansion/addons/settings_f/scripts/keybindings.sqf#L159
