### ISSUE TITLE
AL-6 Pelican drone loadout attribute doesn't properly change the weapon

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/Achilles#389]

**Comment by oOKexOo** [comment]
The change works fine, but the weapon can only be triggered with scripts. Same behavior is observed when you change the loadout in Eden. It's thus a general issue.

**Comment by CreepPork** [comment]
The issue could be bypassed by using the Countermeasures key to dispense the leaflets as leaflets can be dispensed via script but not through the drone interface.
