### ISSUE TITLE
Feature Request: Set Hostage / Captive module

### ISSUE THREAD

**Issue by Lottoungen** [ArmaAchilles/Achilles#399]
Would be nice to see a module that you can put on AI and make them hostages/captives. Similar to the "Make Hostage" option in Eden editor and the ACE Captive module

Perhaps with an option to select the sitting down animation or the standing up one

![0fd310af702cb02ab984108d9c15c25c](https://user-images.githubusercontent.com/44124197/46909905-b82fe700-cf3a-11e8-8033-9a1e2ea87c3f.png)
(Edens "Make Hostage" on the left, ACE captive on the right)

**Comment by CreepPork** [comment]
The module is already implemented as "Surrender Unit" module under AI Behaviours.
