### ISSUE TITLE
Add new control types to Achilles_fnc_showChooseDialog

### ISSUE THREAD

**Issue by oOKexOo** [ArmaAchilles/Achilles#410]
- [ ] "SLIDERTEXT": Combined text input and slider (see #409)
- [ ] "CHECKBOX"

**Comment by CreepPork** [comment]
Color, maybe?

**Comment by oOKexOo** [comment]
Color?

**Comment by oOKexOo** [comment]
And closed in favor of #272

**Comment by CreepPork** [comment]
RGB, like CBA

**Comment by oOKexOo** [comment]
Not sure what CBA feature you are referring to...

**Comment by CreepPork** [comment]
https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#supported-setting-types-_settingtype
