### ISSUE TITLE
BUG: Smoke pillars and grenades do not spawn

### ISSUE THREAD

**Issue by TheRadiumDude** [ArmaAchilles/Achilles#416]
**Arma 3 Version:** `1.88.145263` (stable)  
**CBA Version:** `3.9.0` (stable)  
**Achilles Version:** `1.2.0` (stable)  

**Persistent Smoke Pillars** do not show up properly when spawned, neither do smoke grenades. Issue occured in **Self Hosted Multiplayer.**

**Comment by CreepPork** [comment]
It's #244 again.

**Comment by oOKexOo** [comment]
Many modules no longer get activated automatically in every case since the update. I still don't understand how dedicated vs hosted plays a role, but it apparently does. The solution is the set `BIS_fnc_initModules_disableAutoActivation` to false.
