### ISSUE TITLE
ACE Interaction Menu entries missing prefix

### ISSUE THREAD

**Issue by jonpas** [ArmaAchilles/Achilles#429]
Template is irrelevant, since this is not an issue (yet), but just something I noticed. 

ACE Interaction Menu entries should be prefixed, eg.: https://github.com/ArmaAchilles/Achilles/commit/dcd26808facaffeb74c7ed8b6aa4ac1a3445237c#r3176890

I didn't check other places or SQF action adding.

**Comment by oOKexOo** [comment]
Thx for the note!

**Comment by CreepPork** [comment]
That is the only place where it should be prefixed, no other place uses it. I’ll fix it in the next update.
