### ISSUE TITLE
Damage Buildings: Add Option to Disable Destruction Effects

### ISSUE THREAD

**Issue by mcrow900** [ArmaAchilles/Achilles#430]
I suggest that for the Buildings -> Damage Buildings module you add an option under mean damage called Full (No Destruction Animation), and the just add to the function case 4: {_building setDamage [1, false]};  
This syntax was added in 1.67 and will destroy the building without the destruction effect, good for large scale destruction without crippling the server.

**Comment by oOKexOo** [comment]
Thx for the suggestion. This would certainly help performance.
