### ISSUE TITLE
UBC - ModuleBootcampStage_F -> Module_F

### ISSUE THREAD

**Issue by jonpas** [ArmaAchilles/Achilles#449]
**Arma 3 Version:** `1.88` (stable)  
**CBA Version:** `3.9.1` (stable)  
**Achilles Version:** `3.12.5` (stable)  

**Mods:**
```
- CBA_A3
- Achilles
```

**Description:**
```
13:49:18 Updating base class ModuleBootcampStage_F->Module_F, by achilles\modules_f_achilles\config.bin/CfgVehicles/ModuleHint_F/ (original a3\modules_f_bootcamp\misc\config.bin)
```

**Steps to reproduce:**
- Run the game.

**Where did the issue occur?**
- Environment: All
- Mission: None

**RPT log file:**
- Pasted under description.

**Comment by oOKexOo** [comment]
Thx for the hint. We'll correct the inheritance.
