### ISSUE TITLE
Reinforcement Module Fast Roping bugged

### ISSUE THREAD

**Issue by BloodSoakedBandit** [ArmaAchilles/Achilles#478]
**Arma 3 Version:** `1.90` (stable)  
**CBA Version:** `3.10.1` (stable)  
**Achilles Version:** `1.2.1` (stable)  

**Mods:**
```
- CBA_A3
- Achilles
- ACE
- RHS
- CUP Core/Terrains
- Esseker
- TFAR
- Project OPFOR
- cTab
```
- Note: Keep your test mod set as small as possible. Additional mods for reproducing the issue are only allowed if they are clearly related to the issue.

**Description:**
- Fast Roping in the Reinforcement Module seems not to be working after the latest ACE update, which changed the Fast Rope thing a bit.
When deploying reinforcements in Zeus using the reinforcement module, the AI gets stuck a meter or so in the air twirling at the end of the short rope. This lasts for about 10 seconds and then the AI falls to death. The ropes are extended to the ground at this point, but the rest of the AI just jump to their deaths missing the ropes entirely.
Tested this out with most of the Vanilla and RHS helos. All had the same problem. We've only tried it on Esseker.

**Steps to reproduce:**
- Add a Reinforcement LZ Module in Esseker
- Add a Spawn Reinforcement Module
- Set it to "Helicopter" insert & Fast Rope (ACE).

**Where did the issue occur?**
- Environment: Dedicated Multiplayer

**Comment by neilzar** [comment]
Could you confirm this happens with just the required mods for this functionality? So CBA, Achilles and ACE.

**Comment by BloodSoakedBandit** [comment]
What do you mean?

**Comment by TheRadiumDude** [comment]
We'd like you to try this issue again by loading **only** CBA, Achilles and ACE, preferably Steam versions.
This'll help us verify the cause, thanks in advance.

**Comment by StukaBlyat** [comment]
You should try uninstalling all of the mods and reactivating them one at a time, in order to find which mod (if any) are causing the problem. However, with such a small mod set, i am not sure why the fast roping is bugged.

**Comment by neilzar** [comment]
@StukaBlyat That won't really help, we first need to know if it is still broken with just CBA, ACE and Achilles. Testing if any of the other mods cause the issue irrelevant at this time.

**Comment by oOKexOo** [comment]
> When deploying reinforcements in Zeus using the reinforcement module, the AI gets stuck a meter or so in the air twirling at the end of the short rope. This lasts for about 10 seconds and then the AI falls to death. 

What you are describing is the usual behaviour in MP that is observed since the first time fast-roping was added to the module.  I doubt your claim that it worked before a certain ACE update.
For MP you have to load Advanced Rappelling in addition to get the desired behaviour.

**Comment by StukaBlyat** [comment]
> @StukaBlyat That won't really help, we first need to know if it is still broken with just CBA, ACE and Achilles. Testing if any of the other mods cause the issue is irrelevant at this time.

Yeah, i agree with you on that one.

**Comment by BloodSoakedBandit** [comment]
It was most likely mod a mismatch issue like you said.
Something probably got updated and things broke down.
It has been fixed in the mean time though it seems, since it works now.

**Comment by Totem974** [comment]
Fastrope waypoint with **[Advanced Rappelling - Reworked] or old [Advanced Rappelling]
bug : Waypoint just disapear.
when : Whenever put a fastrop waypoint
