### ISSUE TITLE
Attach to Module; Cant attach objects to vehicles.

### ISSUE THREAD

**Issue by StukaBlyat** [ArmaAchilles/Achilles#480]
This is more of a request then anything. It would be great if we can get objects (buildings, for example) to attach to vehicles. I wanted to have a Pelican attached to one of the frigate objects for a Zeus op in Operation TREBUCHET in order to make it move around. However i do not think it is currently possible. could we get a feature like that in the future?

**Comment by TheRadiumDude** [comment]
As far as I know, it is possible, but quite finicky. I recommend you mess around with it quite a bit, honestly.

**Comment by StukaBlyat** [comment]
> As far as I know, it is possible, but quite finicky. I recommend you mess around with it quite a bit, honestly.

Alright. ill mess around a bit more. thanks!

**Comment by CreepPork** [comment]
If you can reproduce the issue again, feel free to open the issue again. For now, as I deem it resolved, am closing the issue.

**Comment by unhappytroll** [comment]
old trick with disabling simulation still works afaik.
