### ISSUE TITLE
missing global variable option for Bind object to a variable

### ISSUE THREAD

**Issue by empleat** [ArmaAchilles/Achilles#481]
**Arma 3 Version:** 1.9.14571
**CBA Version:** 2.0, not sure it shows when i am trying to use Arma 3 nuke mod
**Achilles Version:** 1.21

**Mods:**
```
- CBA_A3
- Achilles
-Advanced Ordnance
-Arma 3 nuke mod
-Earthquake module
-Altis Maxtide edition
-cup weapons
```

**Description:**
When i select Bind variable to on Object and move it on butterfly, in selecting menu doesn't show global variable. Only public and local.

**Where did the issue occur?**
- Editor (Singleplayer)
- Mission: Altis

**Comment by CreepPork** [comment]
The local variable is a global variable that is only available on the module's executor machine, however, the public variable is broadcasted on all machines via `publicVariable`.

So to summarize, the public variable option is equal to a true global variable on all machines.
