### ISSUE TITLE
Arsenal Breaks itself

### ISSUE THREAD

**Issue by PITSteelers** [ArmaAchilles/Achilles#482]
**Arma 3 Version:** `1.90` 
**CBA Version:** `3.10.1` 
**Achilles Version:** `1.2.1`

**Mods:**
```
- CBA_A3
- Achilles
-D3S Cars Pack
-JSRS SOUNDMOD
```
**Description:**
- Whenever I try to use the physical arsenal object (not the Zeus Arsenal Tool for units nor the arsenal button in a unit's options; those both seem to work fine) as a Zeus-controller unit, I get kicked out to the Zeus interface without entering the arsenal. After this happens, I cannot use the virtual arsenal at all, even via the two other methods that usually work, until the mission is restarted

**Steps to reproduce:**
- Place an arsenal using the "Arsenal" drop-down menu in the Modules section of the Zeus interface.
- Spawn a man unit
- Use Zeus to remote control the unit
- Interact with the arsenal object

**Where did the issue occur?**
- Environment: Dedicated Server

 Mission: Zeus (only tested on altis but I'm almost certain I could reproduce the error on other maps)

**Comment by CreepPork** [comment]
That's sadly how just the Arsenal works and we can't do anything about that. Use the attributes to edit the units loadout.
