### ISSUE TITLE
Modules not spawning in "Modules" Tab

### ISSUE THREAD

**Issue by Timai364** [ArmaAchilles/Achilles#486]
**Arma 3 Version:** `x.xx` (stable / rc / dev)  
**CBA Version:** `3.x.x` (stable / dev + commit hash)  
**Achilles Version:** `x.x.x` (stable / dev + commit hash)  

**Mods:**
```
- CBA_A3
- Achilles
```
- Note: Keep your test mod set as small as possible. Additional mods for reproducing the issue are only allowed if they are clearly related to the issue.

**Description:**
- All Achilles modules are not spawning in in modules tab. They do not seem to be there before placing down a respawn, after placing down a respawn they are there for a second or 2 until the "Place down BLUFOR respawn" objective is complete and then they dissapear.

**Steps to reproduce:**
- Place down respawn

**Where did the issue occur?**
- Environment: Dedicated Multiplayer 
- Mission: All official zeus missions

**Comment by TheRadiumDude** [comment]
Official Zeus Missions do not support Achilles, or any other mods for that matter. You will have to make your own custom mission that supports this.

**Comment by Timai364** [comment]
Since when @TheRadiumDude ? They used to..

**Comment by TheRadiumDude** [comment]
I believe they might not work since Achilles got module settings in Addon Options, and the rule of thumb is Official ZGM missions are generally awful for doing pretty much anything Zeus nowadays.

**Comment by CreepPork** [comment]
Achilles may not work on the first launch, you can try to reload the UI by taking control of an unit.

I may be mistaken but isn’t there a setting in the mission lobby to enable all Zeus addons including unofficial?

But yeah you should more or less avoid the default ZGM missions.

**Comment by CreepPork** [comment]
If you see the issue crop up anywhere else or want to describe the issue more then feel free to reopen the issue, however, I will now close the issue as it's more or less a BI issue.
