### ISSUE TITLE
Zeus unable to edit crates/vehicles inventory after CBA last update

### ISSUE THREAD

**Issue by ZobbyLaMouche** [ArmaAchilles/Achilles#487]
**Arma 3 Version:**

Launcher version: 1.5.145631
Game version: 1.92.145639
Branch: main

**CBA Version:** `3.11.2.190515` stable  
**Achilles Version:** `1.2.1` stable  

**Mods:**
```
- CBA_A3
- Achilles
```
Note : issue occur when only running this 2 mods, persist with any modlist.

**Description:**
- Impossible to edit crate/vehicles inventory in Zeus mode since CBA_A3 update on 2019/05/18 : "current" tab show empty, and items show class names in their tabs (see screenshot). If trying to add this way, items disappear when validating.
Running CBA_A3 only make vanilla Zeus work correctly.

CreepPork_LV on discord pointed me last CBA changelog, where modifications about Zeus and crate/vehicles inventory are notified.

**Steps to reproduce:**
- Load any mission with Achilles active and last CBA_A3 version.

**Where did the issue occur?**
- Environment: self hosted, SP, MP, editor
- Mission: any mission : BI solo missions, campaign, scenarios, self made missions

**RPT log file:**
Didn't saw error, may have missed it, not pro with arma logging :)

![achilles_crates_bug](https://user-images.githubusercontent.com/50776593/57972517-49b57a80-799c-11e9-93ff-e09694b2eea9.jpg)
#

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/issues/1139#issuecomment-494524788
Hope this helps in resolving the issue.

**Comment by CreepPork** [comment]
We’re aware of the issue and saw the PR you made @commy2, and we’ll try to fix the issue as soon as we can. Thanks.
