### ISSUE TITLE
Module description for Custom Modules

### ISSUE THREAD

**Issue by stafmoony** [ArmaAchilles/Achilles#490]
Hey,
I'd like to request a description box for the Custom Modules. 
Something like the description box in editor Modules: https://imgur.com/tIGSWsC

Sometimes it would be nice to describe the usage and effect of a module. 
I think it would be enough if it would be added on the bottom of the module dialog. Though having multiple of these boxes would be cool as well. Whatever is more possible would be fine though!

**Comment by CreepPork** [comment]
Closed in favour of #498.
