### ISSUE TITLE
[Devbranch] Placing vehicle causes error message

### ISSUE THREAD

**Issue by Blutze** [ArmaAchilles/Achilles#511]
**Arma 3 Version:** `1.95.145824` (dev)  
**CBA Version:** `3.11.2.190515` (stable)  
**Achilles Version:** `1.2.2` (stable)  

**Mods:**
```
- CBA_A3
- Achilles
```

**Description:**
Placing a vehicle (probably anything from CfgVehicles, also affects modules etc) as Zeus causes an error message saying "No entry 'bin\config.bin/CfgLocationTypes.HandDrawnCamp'". Afterwards, the vehicle and its crew are using default (NATO/American) voices even when they should be using something custom, like vanilla Greek or RHS Russian.
The RPT file contains further warning messages (line 877ff).

**Steps to reproduce:**
- Open Zeus interface
- Place any vehicle
- Observe error message

**Where did the issue occur?**
- Environment: Self-Hosted Multiplayer (I think, might also be standard SP)
- Mission: https://steamcommunity.com/sharedfiles/filedetails/?id=752850965

**RPT log file:**
- https://gist.github.com/Blutze/76aeb16f8f04262dd334f2f29554417d

**Comment by CreepPork** [comment]
Is the issue still present after Contact's release?

**Comment by Blutze** [comment]
Haven't seen it in 1.94, but I also have not touched the dev branch (1.95) at all since like, a few days before Contact release.

**Comment by CreepPork** [comment]
Then, for now, I'll close the issue. As there aren't any other reports of the issue and as it's regarding the dev branch only. Feel free to reopen the issue, if the issue persists.
