### ISSUE TITLE
Suppressive fire module "Line Up" not working

### ISSUE THREAD

**Issue by EllmansWorld** [ArmaAchilles/Achilles#522]
**Arma 3 Version:** Stable
**CBA Version:** Stable
**Achilles Version:** Stable

**Mods:**
```
- CBA_A3
- Achilles
```
- Note: Keep your test mod set as small as possible. Additional mods for reproducing the issue are only allowed if they are clearly related to the issue.

**Description:**
- The "Line Up" function in the suppressive fire module doesn't make the AI actually line up the target like it use to.

**Steps to reproduce:**
- Place the target module -> Place an AI behind a hill -> Use the suppressive fire module on him and set "Line Up" to yes -> Watch AI fire into the hill.

**Where did the issue occur?**
- Environment: Any environment
- Mission: Any scenario file

**RPT log file:**
- N/A

**Comment by CreepPork** [comment]
This is intended behavior. Line up means that the squad will form a line and engage the target.
